[build]
  command = "miu build"
  publish = "public"

[dev]
  command = "miu dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/netlify/functions/server"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"